/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-primary-fixed": "#00210b",
                "surface": "#f7f9fb",
                "surface-container-highest": "#e0e3e5",
                "on-tertiary-container": "#fffbff",
                "tertiary-fixed": "#e1e0ff",
                "surface-variant": "#e0e3e5",
                "on-surface": "#191c1e",
                "inverse-primary": "#82db98",
                "surface-container": "#eceef0",
                "primary": "#006d33", // Green tone
                "secondary-fixed-dim": "#b9c7e0",
                "on-error-container": "#93000a",
                "outline": "#727785",
                "surface-container-lowest": "#ffffff",
                "surface-container-high": "#e6e8ea",
                "background": "#f7f9fb",
                "on-primary-fixed-variant": "#005225",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#c0c1ff",
                "on-secondary": "#ffffff",
                "surface-bright": "#f7f9fb",
                "on-secondary-fixed-variant": "#3a485c",
                "tertiary": "#4648d4",
                "on-primary": "#ffffff",
                "on-background": "#191c1e",
                "inverse-on-surface": "#eff1f3",
                "secondary-container": "#d5e3fd",
                "primary-fixed": "#9df7b2",
                "on-secondary-fixed": "#0d1c2f",
                "primary-container": "#008a41",
                "on-tertiary-fixed-variant": "#2f2ebe",
                "on-secondary-container": "#57657b",
                "on-error": "#ffffff",
                "inverse-surface": "#2d3133",
                "on-tertiary": "#ffffff",
                "primary-fixed-dim": "#82db98",
                "secondary": "#515f74",
                "outline-variant": "#c1c6d6",
                "on-primary-container": "#fefcff",
                "on-surface-variant": "#414754",
                "tertiary-container": "#6063ee",
                "surface-container-low": "#f2f4f6",
                "surface-dim": "#d8dadc",
                "error": "#ba1a1a",
                "secondary-fixed": "#d5e3fd",
                "surface-tint": "#006d33",
                "on-tertiary-fixed": "#07006c"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
        },
    },
    plugins: [],
}