"""initial schema

Revision ID: eb3b65c74d5f
Revises: 
Create Date: 2026-04-01 17:29:08.686822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3b65c74d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('campaign_ext_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('engagements', sa.Integer(), nullable=True),
    sa.Column('purchases', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source_sheet', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['facebook_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_account_date', 'campaigns', ['account_id', 'date'], unique=False)
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_ext_id'), 'campaigns', ['campaign_ext_id'], unique=False)
    op.create_index(op.f('ix_campaigns_date'), 'campaigns', ['date'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('campaign_lead_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_lead_matches_campaign_id'), 'campaign_lead_matches', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_lead_matches_id'), 'campaign_lead_matches', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_lead_matches_lead_id'), 'campaign_lead_matches', ['lead_id'], unique=False)
    op.add_column('leads', sa.Column('bitrix_id', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('campaign_name', sa.String(length=500), nullable=True))
    op.create_index('ix_leads_account_created', 'leads', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index(op.f('ix_leads_bitrix_id'), 'leads', ['bitrix_id'], unique=True)
    op.create_index('ix_leads_source_status', 'leads', ['source', 'status'], unique=False)
    op.create_index('ix_leads_status_created', 'leads', ['status', 'created_at'], unique=False)
    op.create_foreign_key(None, 'leads', 'facebook_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index('ix_leads_status_created', table_name='leads')
    op.drop_index('ix_leads_source_status', table_name='leads')
    op.drop_index(op.f('ix_leads_bitrix_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_index('ix_leads_account_created', table_name='leads')
    op.drop_column('leads', 'campaign_name')
    op.drop_column('leads', 'account_id')
    op.drop_column('leads', 'bitrix_id')
    op.drop_index(op.f('ix_campaign_lead_matches_lead_id'), table_name='campaign_lead_matches')
    op.drop_index(op.f('ix_campaign_lead_matches_id'), table_name='campaign_lead_matches')
    op.drop_index(op.f('ix_campaign_lead_matches_campaign_id'), table_name='campaign_lead_matches')
    op.drop_table('campaign_lead_matches')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_date'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_ext_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_account_date', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
