/**
 * Mock leads cho ReportDataView — khớp Readdy preview /report-data (15 leads).
 * Sẽ thay bằng API `/api/leads` ở Phase B.
 */

export const MOCK_LEADS = Object.freeze([
    { id: 'FB_1234567890', createdAt: '2025-01-15 08:32:14', name: 'Nguyễn Văn An', email: 'nguyenvanan@gmail.com', status: 'F1', project: 'Vinhomes Grand Park', fanpage: 'Vinhomes Grand Park Official', campaign: 'Vinhomes Grand Park - Q4 2024', adset: 'Adset - Nam 28-45 HCM', ad: 'Video Tour 360° - Căn hộ mẫu 2PN', form: 'Form Lead VGP Tháng 1', source: 'FB' },
    { id: 'FB_1234567891', createdAt: '2025-01-15 09:14:22', name: 'Trần Thị Bình', email: 'tranthib@gmail.com', status: 'Booking', project: 'Vinhomes Grand Park', fanpage: 'VGP Bất Động Sản HCM', campaign: 'Vinhomes Grand Park - Q4 2024', adset: 'Adset - Nữ 30-50 HCM', ad: 'Carousel - Tiện ích nội khu', form: 'Form Lead VGP Tháng 1', source: 'FB' },
    { id: 'TT_9876543210', createdAt: '2025-01-15 10:05:47', name: 'Lê Văn Cường', email: 'levanc@gmail.com', status: 'Đang chăm', project: 'Masteri Waterfront', fanpage: 'Masteri Waterfront TikTok', campaign: 'Masteri Waterfront - TikTok Campaign', adset: 'Adset - Lookalike 1%', ad: 'Video Lifestyle - Masteri', form: 'Form TikTok Masteri', source: 'TT' },
    { id: 'GG_1122334455', createdAt: '2025-01-15 10:48:33', name: 'Phạm Thị Dung', email: 'phamthid@gmail.com', status: 'Deal', project: 'Vinhomes Grand Park', fanpage: 'Google Search VGP', campaign: 'Vinhomes Grand Park - Search Ads', adset: 'Search - Brand Keywords', ad: 'Search - Từ khóa thương hiệu', form: 'Form Google VGP', source: 'GG' },
    { id: 'FB_2233445566', createdAt: '2025-01-15 11:22:09', name: 'Hoàng Văn Em', email: 'hoangvane@gmail.com', status: 'F1', project: 'Masteri Waterfront', fanpage: 'Masteri Waterfront Official', campaign: 'Masteri Waterfront - Facebook Retargeting', adset: 'Retargeting - Website Visitors', ad: 'Retargeting - Khách đã xem website', form: 'Form Retargeting Masteri', source: 'FB' },
    { id: 'GG_3344556677', createdAt: '2025-01-15 13:10:55', name: 'Đỗ Văn Phúc', email: 'dovanphuc@gmail.com', status: 'Booking', project: 'The Metropole Thu Thiem', fanpage: 'Google Display Metropole', campaign: 'The Metropole - Google Display', adset: 'Display - Remarketing', ad: 'Banner - The Metropole Premium', form: 'Form Display Metropole', source: 'GG' },
    { id: 'FB_4455667788', createdAt: '2025-01-15 14:05:18', name: 'Vũ Thị Giang', email: 'vuthig@gmail.com', status: 'Đang chăm', project: 'Eco Green Saigon', fanpage: 'Eco Green Saigon Fanpage', campaign: 'Eco Green - Facebook Lead Ads', adset: 'Adset - Interest Eco Living', ad: 'Lead Form - Nhận báo giá ngay', form: 'Form Lead Eco Green', source: 'FB' },
    { id: 'YT_5566778899', createdAt: '2025-01-15 14:52:41', name: 'Bùi Văn Hải', email: 'buivanh@gmail.com', status: 'F1', project: 'The Metropole Thu Thiem', fanpage: 'The Metropole YouTube', campaign: 'The Metropole - YouTube Ads', adset: 'YouTube - In-stream Ads', ad: 'Video Brand - The Metropole', form: 'Form YouTube Metropole', source: 'YT' },
    { id: 'FB_6677889900', createdAt: '2025-01-15 15:30:27', name: 'Ngô Thị Lan', email: 'ngothilan@gmail.com', status: 'Deal', project: 'Vinhomes Grand Park', fanpage: 'Vinhomes Grand Park Official', campaign: 'Vinhomes Grand Park - Q4 2024', adset: 'Adset - Nam 28-45 HCM', ad: 'Lead Form - Nhận báo giá ngay', form: 'Form Lead VGP Tháng 1', source: 'FB' },
    { id: 'ZL_7788990011', createdAt: '2025-01-15 16:14:03', name: 'Đinh Văn Minh', email: 'dinhvanm@gmail.com', status: 'Đang chăm', project: 'Sunshine City', fanpage: 'Sunshine City Zalo OA', campaign: 'Sunshine City - Zalo Ads', adset: 'Zalo - Targeting HCM', ad: 'Banner Zalo - Sunshine City', form: 'Form Zalo Sunshine', source: 'ZL' },
    { id: 'TT_8899001122', createdAt: '2025-01-16 08:05:12', name: 'Trương Văn Nam', email: 'truongvann@gmail.com', status: 'F1', project: 'Masteri Waterfront', fanpage: 'Masteri Waterfront TikTok', campaign: 'Masteri Waterfront - TikTok Campaign', adset: 'Adset - Lookalike 2%', ad: 'Video Lifestyle - Masteri', form: 'Form TikTok Masteri', source: 'TT' },
    { id: 'FB_9900112233', createdAt: '2025-01-16 09:22:44', name: 'Lý Thị Oanh', email: 'lythio@gmail.com', status: 'Booking', project: 'Eco Green Saigon', fanpage: 'Eco Green Saigon Fanpage 2', campaign: 'Eco Green - Facebook Lead Ads', adset: 'Adset - Interest Green Living', ad: 'Carousel - Tiện ích Eco Green', form: 'Form Lead Eco Green', source: 'FB' },
    { id: 'GG_0011223344', createdAt: '2025-01-16 10:45:30', name: 'Phan Văn Quang', email: 'phanvanq@gmail.com', status: 'Đang chăm', project: 'Vinhomes Grand Park', fanpage: 'Google Search VGP', campaign: 'Vinhomes Grand Park - Search Ads', adset: 'Search - Competitor Keywords', ad: 'Search - Từ khóa cạnh tranh', form: 'Form Google VGP', source: 'GG' },
    { id: 'GG_1122334456', createdAt: '2025-01-16 11:18:55', name: 'Hồ Thị Rạng', email: 'hothir@gmail.com', status: 'F1', project: 'The Metropole Thu Thiem', fanpage: 'The Metropole Google Display', campaign: 'The Metropole - Google Display', adset: 'Display - Interest Luxury', ad: 'Banner - The Metropole Premium', form: 'Form Display Metropole', source: 'GG' },
    { id: 'FB_2233445567', createdAt: '2025-01-16 13:40:08', name: 'Tô Văn Sơn', email: 'tovans@gmail.com', status: 'Deal', project: 'Masteri Waterfront', fanpage: 'Masteri Waterfront Official', campaign: 'Masteri Waterfront - Facebook Retargeting', adset: 'Retargeting - Cart Abandoners', ad: 'Retargeting - Khách đã xem website', form: 'Form Retargeting Masteri', source: 'FB' },
])
